module.exports = {
  type: 'varint',
  mappings: {
    /* Server */
    0: 'client_voice',
    1: 'voice_channel_switch',
    2: 'voice_mute',
    16: 'voice',
    17: 'voice_channel',
    18: 'voice_channel_remove',
    19: 'voice_channel_update',
    /* Client */
    3: 'cooldown',
    4: 'hologram',
    5: 'hologram_update',
    6: 'hologram_remove',
    7: 'nametags_override',
    8: 'nametags_update',
    9: 'notification',
    10: 'server_rule',
    11: 'server_update',
    12: 'staff_mods',
    13: 'teammates',
    14: 'title',
    15: 'update_world',
    20: 'world_border',
    21: 'world_border_remove',
    22: 'wolrd_border_update',
    25: 'ghost',
    28: 'boss_bar',
    29: 'world_border_create_new',
    30: 'world_border_update_new',
    31: 'mod_settings',
    /* Shared */
    26: 'emote_broadcast',
    23: 'waypoint_add',
    24: 'waypoint_remove',
  },
};
